### ISSUE TITLE
Reset password method doesn't throw an exception when a wrong emailAddress is passed 

### ISSUE THREAD

**Issue by priyasharma1** [auth0/auth0-java#103]
When an email address is passed which does not belong to any user, failed log is generated but an exception is not thrown. But in general behavior when using the login method if email or password is wrong, an exception is thrown, So I was excepting a similar behavior,
Please guide me if I am on the wrong track.

**Comment by lbalmaceda** [comment]
The reset password endpoint, which actually just sends a reset password email to the owner, won't fail even if the email doesn't belong to a valid user. This is to prevent email enumeration. When you're doing log in instead, your IP would be blocked if you try several times with a wrong email/password combination.

**Comment by priyasharma1** [comment]
Thanks for the reply @lbalmaceda!
But then how will we be able to find out whether the mail was sent successfully or not.

As the logs generated are as follows
![screenshot from 2018-01-29 18-50-25](https://user-images.githubusercontent.com/14103632/35512299-50e00380-0525-11e8-8571-e0a4ea8fd32b.png)

**Comment by lbalmaceda** [comment]
There's no way for you to know that from the app you're calling the endpoint, no. The error you attached is that no user with that email exists so the call to the reset endpoint fails. But if for some reason the user exists and the email fails to be sent, the error you get in the dashboard would be a different one, talking about the email provider issue.

**Comment by priyasharma1** [comment]
That's right if the email fails even when the user exists, then it's considerable that the error is not returned.
But in case the user doesn't exist then the call should fail and an error should be returned.
What do you think?

**Comment by lbalmaceda** [comment]
This is just an implementation of the Authentication API. As you can see [here](https://auth0.com/docs/api/authentication#change-password) the endpoint itself doesn't return other than that status code `200`. I suggest you contact https://support.auth0.com and open a feature request if that's your concern.

**Comment by priyasharma1** [comment]
Thanks for all the help @lbalmaceda. I will try to handle this our application side.
