### ISSUE TITLE
Algorithm.RSA method deprecation warning

### ISSUE THREAD

**Issue by priyasharma1** [auth0/auth0-java#105]
Hi @lbalmaceda 
I am receiving this warning whenever on every build.

The dependencies I am using are - 
java-jwt-3.3.0,jar
jkws-rsa-0.1.0.jar

Is the support for this method going to be discontinued?

**Comment by lbalmaceda** [comment]
The JWT library is the latest and for JWKs you have 0.3.0 now. Try updating them first and see if the message goes away, or please provide more details as I don't understand the issue. Cheers

**Comment by priyasharma1** [comment]
Yes that worked. Thanks!
