### ISSUE TITLE
com.auth0.RequestProcessor.process is not returning userId

### ISSUE THREAD

**Issue by anandchakru** [auth0/auth0-java#106]
the library takes an effort to make an api call to fetch the **userId**, `userId = fetchUserId(tokens.getAccessToken());`  just to check if its null. If it could return it back to the clients, would save clients making another api call to the auth0

**Comment by lbalmaceda** [comment]
@anandchakru If you need to know the `user id` of a user, you can simply decode the token and get the `sub` claim. Is that your question?

**Comment by anandchakru** [comment]
yes I'm trying to fetch the user id, would `jwts.decode` give me the user id ?

**Comment by lbalmaceda** [comment]
Please read the tokens section of the auth0 site to understand what are they used for and what are they contents. Depending on if you're asking for a custom api audience or not, the access token could be a JWT. The id id token is always a JWT. In any case, take a JWT decoder library like java-jwt and decode the token (must be a JWT) and extract the claim named subject (sub). That value represents the auth0 user id.
