### ISSUE TITLE
Verification via phone using JAVA SDK

### ISSUE THREAD

**Issue by priyasharma1** [auth0/auth0-java#107]
Is there any support to verify user's phone or sent OTP to user's phone using the Java SDK?

**Comment by lbalmaceda** [comment]
What you need is what we call passwordless log in. There's no way to do passwordless log in from this SDK unless you change your hosted login page script to one that supports passwordless and use the authorize url builder class to log in that way. I suggest you read the docs for that on the auth0 site.
If you already have a way to send the OTP, using the management API you should be able to change the phone_verified property of a given user to true.

**Comment by priyasharma1** [comment]
Thanks for the guidance @lbalmaceda.
I'll explore more around the requirements, and figure out a way.

Using the management API could be a solution though.
