### ISSUE TITLE
Add scope example

### ISSUE THREAD

**Issue by gabrielstellini** [auth0/auth0-java#110]
https://community.auth0.com/questions/8857/how-do-i-get-a-user-email-address-via-java-code

> "Creates a request to get the user information associated to a given access token. This will only work if the token has been granted the openid scope."
> 
> Very helpful comment, if only a link to how to do this was included, or some example code existed. Not even test cases seem to exist, so odd.

**Comment by lbalmaceda** [comment]
Probably you've already figured it out by yourself, but just for the record: Depending on which method you're using to log the user in, the name of the method to call changes.

- When redirecting the user to the Universal Login page, you'd need to call [withScope](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/auth/AuthorizeUrlBuilder.java#L86) and customize it when building the authorize URL.
- When calling any `login` method in the AuthAPI you get back an `AuthRequest` instance. That interface has a [setScope](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/net/AuthRequest.java#L32) method you can call.

Some of the requests allow further customization in a generic way, so in those you'd be able to call something like `withParameter(name, value)`. If you only need the email, use a scope of `openid email`.

**Comment by gabrielstellini** [comment]
To further add to the answer, here's how the updated code would look like for [LoginActivity.java](https://github.com/auth0-samples/auth0-android-sample/blob/master/06-Calling-APIs/app/src/main/java/com/auth0/samples/LoginActivity.java)
    
    private void login() {
        Auth0 auth0 = new Auth0(this);
        auth0.setOIDCConformant(true);
        WebAuthProvider.init(auth0)
                .withScheme("demo")
                .withAudience(API_IDENTIFIER)
                .withScope("openid profile email") //added scopes here
                .start(LoginActivity.this, new AuthCallback() {
                    @Override
                    public void onFailure(@NonNull final Dialog dialog) {
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                dialog.show();
                            }
                        });
                    }

                    @Override
                    public void onFailure(final AuthenticationException exception) {
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(LoginActivity.this, "Error: " + exception.getMessage(), Toast.LENGTH_SHORT).show();
                            }
                        });
                    }

                    @Override
                    public void onSuccess(@NonNull final Credentials credentials) {
                        accessToken = credentials.getAccessToken();
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(LoginActivity.this, "Log in: Success", Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                });
    }

**Comment by lbalmaceda** [comment]
@gabrielstellini please note that the code you shared does not correspond to this auth0-java library, but to [the android one](https://github.com/auth0/Auth0.Android) instead.
