### ISSUE TITLE
Set scope when requesting a token for management API

### ISSUE THREAD

**Issue by priyasharma1** [auth0/auth0-java#111]
The token received has all the scopes set to it, thus we wish to restrict the token to just have scope to read, create or update a user or any other scope depending on the situation.
We are using AuthAPI.requestToken to get the token for an audience.

Is there a way to do that?

**Comment by lbalmaceda** [comment]
That method returns you an instance of `AuthRequest`. You should be able to call `request.setScope("read:users")` or whatever scope you need to be granted on that specific call, before calling `execute()`

Also on the Auth0 dashboard if you to to [APIs](https://manage.auth0.com/#/apis/) and click the "Auth0 Management API", you can select under the "Non-Interactive Clients" which clients are allowed to requests tokens for this API and also by clicking the arrow, you can select the scope they are granted by default when no scope is specified in the call.
