### ISSUE TITLE
Examples in readme don't work

### ISSUE THREAD

**Issue by cascer1** [auth0/auth0-java#115]
Hi,

I'm trying to implement some management API functionality in my program but ran into some issues while examining the examples in the readme file.

**TL;DR:** methods return different types than they should, making the examples unusable.

I'll use the example for listing users by email.

```java
Request<UsersPage> request = mgmt.users().listByEmail("johndoe@auth0.com", null);
try {
    UsersPage response = request.execute();
} catch (APIException exception) {
    // api error
} catch (Auth0Exception exception) {
    // request error
}
```

When I enter this code in my editor, I get a warning that the `listByEmail` method returns a different class than is expected (`Request`)

[![1](https://i.eliens.co/1523006206981.png)](https://i.eliens.co/1523006206981.png)

When I then rewrite the request line 

```java
Request request = client.users().listByEmail(email, null);
```

it works, but now running `execute()` on the request returns `Object` instead of `UsersPage`

[![2](https://i.eliens.co/1523006324308.png)](https://i.eliens.co/1523006324308.png)

This error can be resolved by rewriting the request line again

```java
Request<UsersPage> request = client.users().listByEmail(email, null);
```

But now, the `listByEmail` method returns an incompatible object again.

[![3](https://i.eliens.co/1523006427606.png)](https://i.eliens.co/1523006427606.png)

**Comment by cascer1** [comment]
It looks like #102 solves this issue.

**Comment by lbalmaceda** [comment]
Sorry about that. I'll merge that PR now 👍
