### ISSUE TITLE
Resource Owner Password with MFA

### ISSUE THREAD

**Issue by housepage** [auth0/auth0-java#125]
It looks you added functionality  to APIException that allows you to access the values in the error map. I need the `mfa_token` field from this map to implement the resource owner password flow with mfa. When will you be releasing the next version and/or could you possibly release a version that just contains that improvement?

**Comment by lbalmaceda** [comment]
@housepage I wanted to release that earlier but couldn't, and I can't make a release this week. Will probably release the next week as soon as the 2 open PRs are reviewed and merged by my team. 👍

**Comment by housepage** [comment]
@lbalmaceda Thank you for the quick update. That should be in plenty of time for what I'm working on. What's the best way to stay informed if that release is going to slip any further into the future.

**Comment by lbalmaceda** [comment]
We don't have a good channel to communicate those, unfortunately. I'm going to make a release now with the existing non-released changes. 1.6.0 should be available in the next hours, keep an eye on that release PR. I'll close this one.
