### ISSUE TITLE
Missing query filter parmeters on ClientGrantsEntity#list()

### ISSUE THREAD

**Issue by romain-rossi** [auth0/auth0-java#126]
- version 1.5.1

Based on the [Management API v2](https://auth0.com/docs/api/management/v2#!/Client_Grants/get_client_grants) documentation, the method [ClientGrantsEntity](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java)#list() doesn't allow to provide the filtering parameters: per_page, page, audience and client_id.

Or, is there any other way to pass the parameters to the client grants request?

**Comment by lbalmaceda** [comment]
Either I missed them or they weren't available back when I added the methods. I'll leave this open as a reminder so we can add a new method that accept a "filter class" to provide those more easily. 

In the meantime, remember that after calling the method you get a `Request` instance back. You should be able to add query parameters by calling the next method before executing the request:

```java
request.addParameter("audience", audience);
```

**Comment by romain-rossi** [comment]
Thank you @lbalmaceda for your quick answer.

I tried to apply the above workaround but OkHttp doesn't allow body to the GET request method (the added parameters are added as JSon request body when the OkHttp is created).

**Comment by lbalmaceda** [comment]
Sorry, I should have checked before telling you that. You're right, the `addParameter` adds body parameters not the query ones and once the request is created the URL can't be changed so there's no way to add query parameters to a Request as of today. Would be nice to add a `addQueryParameter` method to the `CustomRequest` class in the future. 

Meanwhile, while it sucks having to create the request from 0 you still should be able to achieve that with the following snippet:


```java
//Prepare the base URL
OkHttpClient client = new OkHttpClient.Builder().build();
HttpUrl baseUrl = HttpUrl.parse("https://{your-tenant}.auth0.com");
HttpUrl.Builder builder = baseUrl
        .newBuilder()
        .addPathSegments("api/v2/client-grants");

//Add as many query parameters as required
builder.addQueryParameter("audience", "{your-audience}");
String url = builder.toString();

CustomRequest<List<ClientGrant>> request = new CustomRequest<>(client, url, "GET", new TypeReference<List<ClientGrant>>() {
});
request.addHeader("Authorization", "Bearer " + "{your-mgmt-api-token}");

//Execute the request
try {
    List<ClientGrant> result = request.execute();
} catch (Auth0Exception e) {
    //Handle error
}
```

**Comment by romain-rossi** [comment]
Thanks @lbalmaceda. I was thinking to create the request from scratch. But like you said, "it sucks" :-) (a lot of boilerplate code to "simply" add request parameters).

For now, I don't have a lot of client grants, so I doing the filtering after getting all of them...

Do you know when we could expect this feature?
If it can help, I could provide a pull request to add the request parameters to the  ClientGrantsEntity#list() method (I saw some examples, like [LogEventsEntity](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/mgmt/LogEventsEntity.java)#list())

**Comment by lbalmaceda** [comment]
Adding pagination is part of our backlog for the next 3-4 weeks, and that includes the `ClientGrantsEntity`. We've already started with the `ClientsEntity` as you can see on the open PRs list. Of course if you want you can provide a PR to tackle this one but eventually it will be included, so it depends on how fast you require it. The logic would be similar to the `LogEventsEntity`: A new `list` method should be added that accepts a "filter" class to receive all the params accepted by the endpoint (as the [API Explorer says](https://auth0.com/docs/api/management/v2#!/Client_Grants/get_client_grants)). Feel free to propose a PR if you are in a hurry.

**Comment by romain-rossi** [comment]
3-4 weeks delay is fine for me :-)
Thanks again for you quick replies!
