### ISSUE TITLE
Allow Refresh/Update of Management Api Token

### ISSUE THREAD

**Issue by seanajar** [auth0/auth0-java#131]
As it stands there appears to be no easy way to refresh the `apiToken` of a `ManagementApi`. Since the token used here has an expiration, a new `ManagementApi` requires instantiating with a new valid token when this occurs.

The problem arises with the use of the `OkHttpClient` instantiated with a `ManagementApi`. This leads to a memory leak, as each successive `ManagementApi` creates a new `OkHttpClient` that is never cleaned up.

A similar issue was addressed here: https://github.com/square/okhttp/issues/2846

A setter for the apiToken would alleviate this issue, allowing it to be updated without the need to re-instantiate the `ManagementApi`

**Comment by lbalmaceda** [comment]
Yes, that makes sense. Thanks for raising this up. The new api token would be used on the next call to any of the entities' methods, since it's passed on that call e.g. https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/mgmt/ManagementAPI.java#L160
