### ISSUE TITLE
Support User Search v3 API out of the box

### ISSUE THREAD

**Issue by ivanz** [auth0/auth0-java#133]
Based on this https://auth0.com/docs/users/search/v3#migrate-from-search-engine-v2-to-v3 , this library should support v3 api. 

From what I can see, currently, the `UserFilter` is defaulting to the v2 API here: https://github.com/auth0/auth0-java/blob/faf4adfe0e7a7e14861737a289424f2172d92fcf/src/main/java/com/auth0/client/mgmt/filter/UserFilter.java#L12

**Comment by lbalmaceda** [comment]
@ivanz Yes, this is already on our backlog and we plan to add support for customizing this as well as eventually removing the default value since it's going to be shut down soon. I'll keep this open for visibility.

**Comment by VolkerK** [comment]
I just came around the same issue.
My workaround for now is 
```java
UserFilter filter = new UserFilter();
filter.getAsMap().put("search_engine", "v3");
```
I guess that should work fine, till the new version is released.

**Comment by ivanz** [comment]
Mine:
```
  private class UserFilterV3 extends UserFilter
    {
        public UserFilterV3()
        {
            this.parameters.put("search_engine", "v3");
        }
    }
```
