### ISSUE TITLE
Javadoc for this API ?

### ISSUE THREAD

**Issue by MarcAgate** [auth0/auth0-java#139]
Hi, I cannot find a link to any javadoc for this API, should I generate it by myself or is it published somewhere ?

**Comment by lbalmaceda** [comment]
We don't publish them anywhere but are included in the dependency itself. e.g. for 1.7.0 if you look in your maven folder you'll find them.

```
~/.m2/repository/com/auth0/auth0/1.7.0
auth0-1.7.0-javadoc.jar  auth0-1.7.0.jar
auth0-1.7.0-sources.jar  auth0-1.7.0.pom
```

Direct [download link](http://search.maven.org/remotecontent?filepath=com/auth0/auth0/1.7.0/auth0-1.7.0-javadoc.jar) obtained from [maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.auth0%22%20a%3A%22auth0%22)

**Comment by MarcAgate** [comment]
Thanks ! (I had generated it already,but it's good to know)
