### ISSUE TITLE
Scope issue during creation of custom email template

### ISSUE THREAD

**Issue by yass-arafat** [auth0/auth0-java#145]
While trying to create, update email template in auth0 i am getting scope issue saying 

> Request failed with status code 403: Insufficient scope, expected any of: create:email_templates

although the scope is set in the API's Scope settings.
![screenshot-manage auth0 com-2018 08 13-19-52-15](https://user-images.githubusercontent.com/23176168/44035952-7925118a-9f32-11e8-8045-4654ae20291f.png)

My code is 
```String[] scopeArray = new String[]{"create:email_templates"};
mgmtAPI .clientGrants().create(client_id, dbConnectionName, scopeArray);
Request<EmailTemplate> request = mgmtAPI.emailTemplates().create(template);
EmailTemplate res = request.execute();
```
Did i miss anything or is there any way to do it?

**Comment by lbalmaceda** [comment]
The JSON web token you're using to instantiate the `MgmtAPI` must have those scopes granted. You can do that using the `AuthAPI` as explained in the readme. Remember to request the proper `audience` and `scope` when you ask for the JWT. 

More about tokens: https://auth0.com/docs/api/management/v2/tokens

**Comment by yass-arafat** [comment]
Thanks for your reply. The issue was with the of my JWT token. I checked here https://jwt.io/ and found that my latest added scope are not added in my API Token. Adding thing from auth0's API dashboard, it worked.
