### ISSUE TITLE
README spelling URL

### ISSUE THREAD

**Issue by Aiden007700** [auth0/auth0-java#156]
url => URL
URL when not part of a code snippet should be URL.

**Comment by vaibhavsingh1993** [comment]
@Aiden007700 is correct, added another PR (on top of #157).
 https://github.com/auth0/auth0-java/pull/159

**Comment by Soundug** [comment]
Is this issue still open?

**Comment by lbalmaceda** [comment]
No. Seems this is already fixed with #159. Thanks
