### ISSUE TITLE
v1.9.0 not in maven?

### ISSUE THREAD

**Issue by joelash** [auth0/auth0-java#160]
Looks like version 1.9.0 didn't get uploaded to maven.

<img width="1730" alt="cleanshot 2018-10-11 at 12 54 24 2x" src="https://user-images.githubusercontent.com/64599/46823814-d0461180-cd54-11e8-8a9a-3c0f9cc647a1.png">

**Comment by lbalmaceda** [comment]
@joelash True. I just synced it. Expect it in a few hours.
