### ISSUE TITLE
grant_types is missing from com.auth0.json.mgmt.client.Client

### ISSUE THREAD

**Issue by adrian-baker** [auth0/auth0-java#162]
`grant_types` is missing from `com.auth0.json.mgmt.client.Client`, which means it's not possible to update this field using this sdk.

**Comment by lbalmaceda** [comment]
Thanks! It's indeed missing https://auth0.com/docs/api/management/v2#!/Clients/patch_clients_by_id

Feel free to make a PR to add this and I'll review it.
