### ISSUE TITLE
com.auth0.exception.APIException for Grant type gives bad URL

### ISSUE THREAD

**Issue by Jazzepi** [auth0/auth0-java#165]
com.auth0.exception.APIException: Request failed with status code 403: Grant type 'http://auth0.com/oauth/grant-type/password-realm' not allowed for the client.

https://auth0.com/oauth/grant-type/password-realm leads to a 404 page. Either the page should be restored, or the link should be changed. I'd put in a PR but I have no idea what the link is suppose to be.

**Comment by Jazzepi** [comment]
Maybe this? https://auth0.com/docs/applications/application-grant-types

**Comment by lbalmaceda** [comment]
That is the grant type value, not necessarily a valid URL. The error comes from the authentication server.
