### ISSUE TITLE
Maven artifactId

### ISSUE THREAD

**Issue by scholza** [auth0/auth0-java#18]
the artifactId mentioned in the readme is not consistent with the artifact published in maven repo:
* the readme states "auth0-java"
* the actual artifact in maven is "auth0" - without the "-java"

The maven-central icon is correct (that's how I actually found the artifact). Maybe it is more a problem with the build than the readme as "auth0" seems a bit generic for an artifactId.

**Comment by hzalaz** [comment]
@scholza Thanks for the heads up, just updated the README to use the correct artifact id, we forgot to fix it after the release.
