### ISSUE TITLE
JWTDecoder NotSerializableException

### ISSUE THREAD

**Issue by pavloskrontiras** [auth0/auth0-java#184]
While trying to integrate auth0 in a test application that gets deployed to the Google AppEngine, the following exception occurs on this line of the code:

`SecurityContextHolder.getContext().setAuthentication(tokenAuth);
`
I used the sample code provided in the auth0 documentation.

`javax.servlet.ServletException: java.lang.RuntimeException: java.io.NotSerializableException: com.auth0.jwt.JWTDecoder at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:300) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) at org.eclipse.jetty.server.Server.handle(Server.java:539) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333) at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:202) at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81) at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:123) at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:699) at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:661) at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:631) at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:825) at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:273) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.RuntimeException: java.io.NotSerializableException: com.auth0.jwt.JWTDecoder at com.google.apphosting.runtime.SessionManagerUtil.serialize(SessionManagerUtil.java:32) at com.google.apphosting.runtime.DatastoreSessionStore.createEntityForSession(DatastoreSessionStore.java:69) at com.google.apphosting.runtime.DatastoreSessionStore.saveSession(DatastoreSessionStore.java:91) at com.google.apphosting.runtime.jetty9.SessionManager$AppEngineSession.save(SessionManager.java:141) at com.google.apphosting.runtime.jetty9.SaveSessionListener.requestComplete(SaveSessionListener.java:27) at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:175) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:296) ... 12 more Caused by: java.io.NotSerializableException: com.auth0.jwt.JWTDecoder at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) at java.util.HashMap.internalWriteEntries(HashMap.java:1786) at java.util.HashMap.writeObject(HashMap.java:1363) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) at com.google.apphosting.runtime.SessionManagerUtil.serialize(SessionManagerUtil.java:29) ... 22 more`

**Comment by lbalmaceda** [comment]
> I used the sample code provided in the auth0 documentation.

I'm not familiar with Google App Engine. Can you please share the link to that auth0 article?

**Comment by pavloskrontiras** [comment]
https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc

**Comment by Bini-Saju** [comment]
Is this issue solved?. Having the same exception 'java.io.NotSerializableException: com.auth0.jwt.JWTDecoder'

**Comment by lbalmaceda** [comment]
I'm not sure this will work, but I have the feeling that GCE has serialization issues with code using anonymous inner classes. Anyway, I went through the sample code and couldn't find any anonymous class being instantiated. Can you please check your app, if you have added something extra from the sample base code?

**Comment by jimmyjames** [comment]
I tried deploying the [Spring Security MVC sample](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/tree/master/01-Login) to AppEngine, and it was working fine in my case with this basic appengine configuration:

```yaml
runtime: java
env: flex

runtime_config:  # Optional
  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  
manual_scaling:
  instances: 1
```

I could see issues arising when configured with more than one instance, if `session_affinity` isn't set to `true` (which does limit the ability to load balance optimally, but that example is not stateless). 

Since I wasn't able to reproduce with this basic configuration, I don't think this issue is specific to the SDK so I'm going to close the issue. I would recommend you to checkout https://auth0.com/support for additional assistance, or perhaps work with Google AppEngine support to figure out what's going on.
