### ISSUE TITLE
Feature Request: Support for Rules Config endpoints

### ISSUE THREAD

**Issue by fritzdj** [auth0/auth0-java#185]
We have a use case where we would like to hit the GET, DELETE, and PUT rules-configs endpoints and would like this added to the client library.

GET: https://auth0.com/docs/api/management/v2#!/Rules_Configs/get_rules_configs
DELETE: https://auth0.com/docs/api/management/v2#!/Rules_Configs/delete_rules_configs_by_key
PUT: https://auth0.com/docs/api/management/v2#!/Rules_Configs/put_rules_configs_by_key

**Comment by lbalmaceda** [comment]
@fritzdj I'll add this to our backlog. Note we can't provide any ETA on resolving this. But you're encouraged to propose a PR with a solution (probably mimicking what we have done for other endpoints).
