### ISSUE TITLE
Query part of UserFilter is not supported in UsersEntity#get()

### ISSUE THREAD

**Issue by menulis** [auth0/auth0-java#188]
auth0-java version: 1.10.0

I use app_metadata to associate Auth0 users to certain sites:

```
app_metadata:
  "sites": {
    "12345": {
    // ...
    },
    "54321": {
    // ...
    }
  }
```
Say I want to get a list of users that are associated with site 12345, i.e. key "12345" is part of app_metadata.sites as per Lucene query syntax:

```
mgmt.users().list(
    UserFilter()
        .withSearchEngine("v3")
        .withQuery("app_metadata.sites.12345:*")
).execute()
```
This works as expected and returns only the users matching the provided query on app_metadata. More specifically, the URL that `UsersEntity#list()` builds is the following:

`https://{TENANT}.eu.auth0.com/api/v2/users?q=app_metadata.sites.12345%3A*&search_engine=v3
`

I have third parties, each associated with a site id. I want to expose a function that fetches information about a given user, identified by Auth0 userId. I was hoping to reuse the same UserFilter above to make sure that only users associated with one specific site id can be fetched. Hence the code fragment looks like that:

```
mgmt.users().get(userId,
    UserFilter()
        .withSearchEngine("v3")
        .withQuery("app_metadata.sites.12345:*")
).execute()

```

The problem is that the code above not only fetches users that do have "12345" key as part of their app_metadata.sites, but also about the ones that do not. In other words, the query part of the filter does not seem to work as expected.

I first thought the reason is that UsersEntity#get() incorrectly encodes the query filter and the URL becomes the following:

`https://{TENANT}.eu.auth0.com/api/v2/users/auth0%7Cdeadbeefdeadbeefdeadbeef?q=app_metadata.sites.12345%253A*&search_engine=v3`

This is because there is no check for `KEY_QUERY.equals(e.getKey())` as opposed to `UsersEntity#list()` and hence the url encoded colon %3A becomes %253A as % is url encoded to %25.

The fix for it would be to reuse the same check as in `UsersEntity#list()`.

However, calling the fixed URL (with %253A replaced to %3A) directly yield to the same results, i.e. the q= part is ignored. This is despite the fact that such limitation is not mentioned in the [documentation](https://github.com/auth0/auth0-java).

**Comment by lbalmaceda** [comment]
`users().list()` would perform a GET request to obtain a paged **list of users** that match the search criteria (what you typed in the query). 

`users().get()` would perform a GET request to obtain a **single user object** with the given userId. In this case, the query parameter is ignored by the server as it's not accepted. You can use the `UserFilter` to decide which fields are going to be returned in the response. The accepted parameters are documented in the API [endpoint](https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id). 

To achieve what you want, either find a query that includes the user-id and use the `list()` method, or search by user-id and filter locally.

**Comment by menulis** [comment]
Thanks for the reply, @lbalmaceda. Don't you think that in this case the [documentation](https://github.com/auth0/auth0-java) should be updated accordingly? Currently it says _You can pass an optional Filter to narrow the results in the response_, which is misleading for the `users().get()` case.
