### ISSUE TITLE
Add Metadata Field to Connection Object

### ISSUE THREAD

**Issue by AlisonT1230** [auth0/auth0-java#205]
We would like to be able to use auth0-java to configure a connection in Auth0 with connection metadata.  Currently, the implementation of the Connection object does not have a metadata field while the API supports it.

Referring to connections API documentation: https://auth0.com/docs/api/management/v2#!/Connections/get_connections

I'm aiming to have a pull request in soon (within a few days) with this addition.

**Comment by lbalmaceda** [comment]
Sounds good! Let me know when the PR is ready and we will review it from this side.

**Comment by AlisonT1230** [comment]
PR is ready: https://github.com/auth0/auth0-java/pull/206
Thanks for the quick reply & support!

**Comment by AlisonT1230** [comment]
Is there an ETA for the next release that will include these changes?
