### ISSUE TITLE
Retrieving the User Profile using a refreshed token returns an empty object and errors

### ISSUE THREAD

**Issue by tomrom95** [auth0/auth0-java#207]
### Description
After retrieving user credentials for the first time, we can successfully use the returned token to get the User Profile using the `AuthenticationAPIClient.userInfo(token)` method. However, after the token is refreshed, calling the `userInfo` method with the refreshed token results in the following exception:

```
 com.google.gson.JsonParseException: user profile json is not a valid json object
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:21)
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:17)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
        at com.auth0.android.request.internal.SimpleRequest.execute(SimpleRequest.java:111)
```
The reason for this is because the `/userInfo` endpoint is returning an empty JSON object (`{}`) back and this cannot be parsed. We have additionally found that an empty JSON object is being returned because the refreshed token does not contain the scopes necessary to fetch the user's profile (`openid` and `profile`). Using the CredentialsManager, there's also no way to pass in these scopes when fetching/refreshing the token:
```java
void getCredentials(@NonNull final BaseCallback<Credentials, CredentialsManagerException> callback) {
```

Is there any way we can pass in these scopes or enable the refreshed token to have the same scope as the original token?

### Environment
- Auth0 1.15.1
- Java 8

### Reproduction

Call `CredentialsManager.getCredentials()` after a token has expired and then use the token to call `AuthenticationAPIClient.userInfo(token).execute()`. This will result in a JsonParseException

**Comment by lbalmaceda** [comment]
@tomrom95 are you sure this is the right repo? Those classes are not part of this SDK.

**Comment by tomrom95** [comment]
Ah part of Android. Will move the issue there
