### ISSUE TITLE
Feature Request: Add support for RBAC

### ISSUE THREAD

**Issue by lukebonderevel** [auth0/auth0-java#213]
The Resource Server entity on the Auth0 Management API has support for RBAC through the `enforce_policies` and `token_dialect` properties in the body JSON. [See documentation](https://auth0.com/docs/api/management/v2#!/Resource_Servers/post_resource_servers)

I request that the Auth0 Java SDK be extended to integrate with RBAC capabilities.

Thanks!

**Comment by lbalmaceda** [comment]
I think this was solved with https://github.com/auth0/auth0-java/pull/214. Did you find any other missing property @lukebonderevel ?

**Comment by lukebonderevel** [comment]
You are correct @lbalmaceda. Thanks!
