### ISSUE TITLE
Management API Client ?

### ISSUE THREAD

**Issue by drazzib** [auth0/auth0-java#22]
Hi!

What is current plan (and associated ETA) for implementing Management API Client in this project ?
https://auth0.com/docs/api/v2

Regards,

**Comment by hzalaz** [comment]
@drazzib it's in our plans but not in the short term, we'll start adding some of them little by little starting with the users endpoint. What api methods do you need?

**Comment by drazzib** [comment]
Hi @hzalaz !

I've started implementing /api/v2/users (list/search + get + add).
Would you be interested in a PR with my actual code ?

Best regards,

**Comment by hzalaz** [comment]
@drazzib sure

**Comment by pocman** [comment]
Hi, 
I would really need the PATCH	/api/v2/users/{id}

**Comment by uded** [comment]
Any chance to get some traction on this? Management API is a huge miss here...
