### ISSUE TITLE
Bug: Illegal properties included in resource server update request cause APIException

### ISSUE THREAD

**Issue by HSAR** [auth0/auth0-java#224]
### Description

`APIException` is thrown when attempting to update a Resource Server. The detailMessage given is `Request failed with status code 400: Payload validation error: 'Additional properties not allowed: id,identifier'.`

### Prerequisites

- [x] I have checked the documentation for this library in the README.
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-java/issues) and [PRs](https://github.com/auth0/auth0-java/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository [Add links to other related].

### Environment

- Version of this library used: `1.14.1`
- Version of Java used: `1.8.0_121`
- Version of Kotlin used: `1.3.41`

### Reproduction

Execute the following with a properly initialised `ManagementAPI` object:
(Apologies for Kotlin)
`val resourceServer = managementAPI.resourceServers().get(resourceServerID).execute()
managementAPI.resourceServers().update(resourceServerID, resourceServer).execute()`

Resulting exception:
`com.auth0.exception.APIException: Request failed with status code 400: Payload validation error: 'Additional properties not allowed: id,identifier'.`

### Details

Looking at the request, I intuitively think that the `APIException` is completely right - there are extra properties (`id` and `identifier`) included which should not be. See below:

(Now with less sensitive data!)
![image](https://user-images.githubusercontent.com/985911/63108653-4facfe80-bf7f-11e9-8340-1c601a80afd2.png)

The online documentation [here](https://auth0.com/docs/api/management/v2#!/Resource_Servers/patch_resource_servers_by_id) suggests `id` and `identifier` should not be included.

**Comment by lbalmaceda** [comment]
@HSAR This is not a bug. The API error is correct, you are sending parameters that can't be changed once the entity was created on the server side. Because there's a single POJO class for that entity for all the requests, you need to use the [alternate constructor](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/ResourceServer.java#L48) that doesn't require any parameters and set only the values you want to change. Remember this is a PATCH, not a PUT request.

**Comment by HSAR** [comment]
That was the issue. I feel rather foolish, but such is life.

Thanks for your help, @lbalmaceda.

**Comment by lbalmaceda** [comment]
@HSAR No worries. Please open a new issue if you encounter something else or have a new question.
