### ISSUE TITLE
Dependency issue when using from scala library

### ISSUE THREAD

**Issue by marioosh** [auth0/auth0-java#235]
I'm using auth0 with scala (SDK 2.12.10) and got that error message during building the project:
```
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.9.9 requires Jackson Databind version >= 2.9.0 and < 2.10.0

```
I see that Jackson Databind since version 1.14.3 is set to 2.10.pre3, so it's incompatible with Scala library.

**Comment by marioosh** [comment]
issued by some others dependencies...

**Comment by darkknight100** [comment]
@marioosh Can you give some example regarding how did you import the right version explicitly?
