### ISSUE TITLE
com.auth0.json.mgmt.client.Client missing initiate_login_uri property

### ISSUE THREAD

**Issue by kevinrs5855** [auth0/auth0-java#238]
### Description

I am a member of the IAM team at my company and we are an Auth0 customer.  We are attempting to create applications in Auth0 for each of our own applications/services and want to specify the initiate_login_uri for each application.  This is for all the reasons detailed at https://auth0.com/docs/universal-login/default-login-url.  

### Prerequisites

- [ X] I have checked the documentation for this library in the README.
- [ X] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [X ] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-java/issues) and [PRs](https://github.com/auth0/auth0-java/pulls).
- [X ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [ X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [ X] I am reporting this to the correct repository [Add links to other related].

### Environment

Please provide the following:

- Version of this library used: latest
- Version of Java used:8
- Additional libraries that might be affecting your instance: N/A

### Reproduction

Notice the missing attribute in https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/client/Client.java

**Comment by lbalmaceda** [comment]
👋 Thanks for the report! We've reviewed this and agree it's an issue. We're tracking this internally and will come up with a solution soon.

**Comment by kevinrs5855** [comment]
@lbalmaceda  & @damieng thanks for fixing this!  When do you plan on releasing master, i.e. 1.16.0?

**Comment by lbalmaceda** [comment]
@kevinrs5855 👋 Sometime this week! We need to include a few more changes. It will be on a minor 👍
