### ISSUE TITLE
Add sources to Permission objects returned from ManagementAPI users().listPermissions call

### ISSUE THREAD

**Issue by BLWedge09** [auth0/auth0-java#246]
### Describe the problem you'd like to have solved

Auth0 has added sources to permissions when called from the /api/v2/users/{id}/permissions endpoint. These optional sources are not included in the Permission object that is returned using this Java library.

A Permission can have a list of sources, The source Object is structured as such:

       {
          "source_id": "rol_xxxxxxxxxxxxxxxx",
          "source_name": "ROLE-NAME",
          "source_type": "DIRECT"
        },

### Describe the ideal solution

Add source objects to Permission objects returned when calling users().listPermissions from the ManagementAPI.

## Alternatives and current work-arounds

No good alternative that I see currently.

### Additional context

![auth0PermissionSources](https://user-images.githubusercontent.com/1584228/79133222-4889fa80-7d71-11ea-8855-f3df9b92680c.png)

**Comment by lbalmaceda** [comment]
👋 @BLWedge09 I can't find the change that you mention on the swagger API docs. May I ask where you took this from?

**Comment by BLWedge09** [comment]
@lbalmaceda Sorry, I did actually include the wrong screenshot on my original post. On this page: https://auth0.com/docs/api/management/v2#!/Users/get_permissions
See the Optional Sources in the response schema.  If I actually make the call on that page or from postman,  I get back a block like this for each assigned permission. THere is a separate source block for every Role that the user has assigned that includes the permission as well as a source object for if the permission was directly assigned instead of via a role.  That direct assignment is the reason I need this.:

`{
        "permission_name": "PERMISSIONNAME",
        "description": "PERMISSIONDESCRIPTION",
        "resource_server_name": "APINAME,
        "resource_server_identifier": "APIIDENTIFIER",
        "sources": [
            {
                "source_id": "ROLEID",
                "source_name": "ROLENAME",
                "source_type": "ROLE"
            },
            {
                "source_id": "",
                "source_name": "",
                "source_type": "DIRECT"
            }
        ]
    },`

**Comment by lbalmaceda** [comment]
>See the Optional Sources in the response schema. 

The screenshot would be this then, but still, I don't see the source attributes on the swagger docs. So this comes as part of the response? I'll check with the API team to see if they can update the docs and tell which of the attributes are "required", and if that's correct, I'll take this request as well to my team to include it on the SDK.
 
![image](https://user-images.githubusercontent.com/3900123/79912161-f8a5d600-83f7-11ea-94ce-eacabe97113b.png)

**Comment by lbalmaceda** [comment]
WAIT. This is Users!! I confused it with Roles. I see the optional "sources" property now. 
![image](https://user-images.githubusercontent.com/3900123/79912563-99949100-83f8-11ea-8c5f-8a1a15dcea47.png)

I'll still need to check with the API team for them to clarify the required attributes on that property. I'll circle back. Thanks !

**Comment by BLWedge09** [comment]
@lbalmaceda Correct, it's under users. I was hoping it would be as simple as just pulling in new swagger docs and recompiling, but if that page is a representation of the swagger docs, the sources might not be there as of right now.  This would be really useful information for a project that I'm working on. Trying to figure out if a user has a permission because it came from a rule or not is a process of elimination right now.  This would allow me insight into just where they are getting each permission from.

Thanks for taking a look. Please let me know what you find.

**Comment by lbalmaceda** [comment]
I've received the details from the team that added the API. It seems the possible values for the type are DIRECT and ROLE. And only in the case of ROLE, the other two properties will be present. For DIRECT, they are empty.

I'll make the changes to include this in the following week.

**Comment by BLWedge09** [comment]
@lbalmaceda 

> I've received the details from the team that added the API. It seems the possible values for the type are DIRECT and ROLE. And only in the case of ROLE, the other two properties will be present. For DIRECT, they are empty.
> 
> I'll make the changes to include this in the following week.

**Comment by BLWedge09** [comment]
@lbalmaceda Thank you so much. Sorry, I accidentally clicked to close it.  Been a long day.

**Comment by BLWedge09** [comment]
@lbalmaceda Any idea when I might be able to expect this to be added?  I don't want to continue to pester you. This just happened to become a bit of a blocker on a particular piece of an application I'm working on.

**Comment by lbalmaceda** [comment]
@BLWedge09 No worries at all, feel free to ping again if we miss your message. I understand these properties are read-only, is that correct? I forgot to ask that bit. 

We have this on the backlog. I'd expect this to be added during this week, but since we have higher priority tasks it might take a few more days.

**Comment by BLWedge09** [comment]
> @BLWedge09 No worries at all, feel free to ping again if we miss your message. I understand these properties are read-only, is that correct? I forgot to ask that bit.
> 
> We have this on the backlog. I'd expect this to be added during this week, but since we have higher priority tasks it might take a few more days.

Correct. They are definitely read only.

**Comment by lbalmaceda** [comment]
I've created #254. To my understanding, and as per discussed above, a `Permission` cannot have its sources set.
Take a look and let me know if that works for you.

**Comment by BLWedge09** [comment]
> Take a look and let me know if that works for you.
Yep. That looks like exactly what I need.
