### ISSUE TITLE
Mgmt API Connection Class missing fields returned as part of REST API

### ISSUE THREAD

**Issue by kevinrs5855** [auth0/auth0-java#252]
### Description
The auth0-java sdk Connection class does not include the display_name and last_password_reset fields as part of the Connection class.  These fields are included in the Auth0 REST API responses.

See https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/Connection.java is missing the display_name documented here, https://auth0.com/docs/api/management/v2#!/Connections/patch_connections_by_id.  

### Reproduction
Call the Mgmt API to fetch a connection by id, 
Notice that in postman the response includes the fields but in the Java SDK they are missing.

### Environment
Using auth0-java version auth0-1.15.0.jar

**Comment by lbalmaceda** [comment]
👋 Thanks for the report! We've reviewed this and agree it's an issue. We're tracking this internally and will come up with a solution soon.

**Comment by lbalmaceda** [comment]
@kevinrs5855 Reading again today your report, I couldn't find the `last_password_reset ` on the Connection API2 docs. I think you refer to the User's object for that. It was added here https://github.com/auth0/auth0-java/pull/256
