### ISSUE TITLE
Version 1.16.0 is not available on Maven Central

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [auth0/auth0-java#253]
Hello there. Thank you for offering this great library. Version 1.16.0 does not seem to be uploaded to Maven Central. Try to add version 1.16.0 (as listed on the README) to a Gradle file produces errors which may cause confusion. Could you please upload the artefact to the Maven repository? Thank you 😄

**Comment by lbalmaceda** [comment]
thanks for calling it out! I just synced this. You should see it in the next hour.
