### ISSUE TITLE
TokenHolder should hold `scope` entry [SDK-2000]

### ISSUE THREAD

**Issue by mistriel** [auth0/auth0-java#276]
Hi,
The Auth0 response for getting `access_token` also contains `scope` parameter in the returned JSON.
Yet, in "master" (Pardon my French) its still not reflected in the DTO object [TokenHolder](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/auth/TokenHolder.java).

For example, see the following response:

```json
{
    "access_token": "some-jwt-token-base64-string",
    "scope": "read:client_grants create:client_grants delete:client_grants update:client_grants read:users update:users delete:users create:users",
    "expires_in": 2592000,
    "token_type": "Bearer"
}
```

i can do a quick pull request if needed

**Comment by lbalmaceda** [comment]
Sounds like a good addition. Would you mind sending that PR, please?

**Comment by lbalmaceda** [comment]
Tracking internally `SDK-2000`
