### ISSUE TITLE
UrlJwkProvider missing jack ObjectMapper

### ISSUE THREAD

**Issue by colymore** [auth0/auth0-java#277]
### Description

1.20.0 version of the auth0 SDK is not importing ObjectMapper class from jackson in lubrary com.auth:jwks-rsa0.9.0

### Reproduction

Just install 1.20.0 version.

<img width="1439" alt="Screen Shot 2020-08-02 at 11 48 28" src="https://user-images.githubusercontent.com/572601/89125613-17ffd500-d4b6-11ea-8a9b-773d28c8bf43.png">

### Environment

> Please provide the following:

-  Version 1.2.0
- Using ktor 1.3.2 with gradle.

**Comment by lbalmaceda** [comment]
This library doesn't have `com.auth:jwks-rsa:x.y.z` as a dependency. You can check the dependencies of this library [here](https://github.com/auth0/auth0-java/blob/master/build.gradle#L63-L67). 
Are you sure this is the right repo?

**Comment by colymore** [comment]
Sorry you are right, I had a conflict bnetween this lib and the last version of ktor_jwt which is importing other auth0 version.
