### ISSUE TITLE
No support for 'includeEmailInRedirect' in post_email_verification [SDK-1999]

### ISSUE THREAD

**Issue by SteveG0** [auth0/auth0-java#278]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, this was reported on community (https://community.auth0.com/t/emailverificationticket/47429) 

There does not appear to be anything related to 'includeInEmailRedirect' in this class - https://github.com/auth0/auth0-java/blob/b23edd290e68e7e88ae6b2de61be75e7ffe9bc3e/src/main/java/com/auth0/json/mgmt/tickets/EmailVerificationTicket.java

Whereas in the Management API docs this is a supported parameter - https://auth0.com/docs/api/management/v2/#!/Tickets/post_email_verification

### Reproduction

Attempt to set 'includeInEmailRedirect' parameter using mgmt.tickets() methods, parameter has nothing to match to in class.

### Environment

> Please provide the following:

- **Version of this library used:** - 1.20
- **Version of the platform or framework used, if applicable:** N/A
- **Other relevant versions (language, server software, OS, browser):** N/A
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by lbalmaceda** [comment]
Good catch. Do you think you can send a PR @SteveG0?

**Comment by lbalmaceda** [comment]
Tracking internally under `SDK-1999`
