### ISSUE TITLE
UserProfile.getExtraInfo() always null

### ISSUE THREAD

**Issue by pdelorme** [auth0/auth0-java#31]
Im using auth0-java in a SpringBoot application with ng2 on the front side.
Authentication and authorisation goes well but when I can't get user info from the JWT token on the server.
While UserProfile is retrieved without problems, the profile extraInfo is always Null even though I get this info through the [support page](https://auth0.com/docs/api/authentication#!#post--tokeninfo)

see this example :

```
final Request<UserProfile> request = client.tokenInfo(token.getJwt());
final UserProfile profile = request.execute();
logger.trace("JWT.profile:nickname :"+profile.getNickname()); // OK
Map<String, Object> extraInfo = profile.getExtraInfo();
logger.trace("JWT.profile.size :"+extraInfo.size()); // NULL POINTER
```

any suggestions ?
thanks.

**Comment by lbalmaceda** [comment]
Please check our latest version as it's a bit more generic. You'll still need to know each property name and perform a null check.
