### ISSUE TITLE
Provide object to configure Client refresh token settings

### ISSUE THREAD

**Issue by JakeUskoski** [auth0/auth0-java#318]
### Describe the problem you'd like to have solved

Currently the refresh token settings for a client cannot be modified via the Java SDK, which makes managing the refresh token behaviour and settings impossible with the SDK as-is.

### Describe the ideal solution

The ideal solution would be the client class containing a refresh token object which can be configured, similarly to how the mobile settings on a client are configured (Android & iOS). The configuration at the time of creating this issue is:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/12035372/98600277-4c501200-22ab-11eb-8afa-ceafecfea715.png">

## Alternatives and current work-arounds

We're currently extending the Client class and adding a refresh token object (currently a string-object map) to send as a part of the payload when creating a client.

### Additional information, if any

There was a change recently introduced in Auth0 where the default setting of refresh token behaviour when not provided became Rotating instead of Non-Rotating, which caused havoc for us (the company I work for). We couldn't resolve this by setting our own sensible defaults via the Java SDK due to the lack of configuration options for the refresh token, and thus were forced to extend the client object provided in the SDK.

**Comment by jimmyjames** [comment]
Thanks for raising this and including details. We are discussing adding this functionality to this and other SDKs (we recently received a [similar issue](https://github.com/auth0/auth0.net/issues/450) to the .NET SDK). Will follow up with our plans here.

**Comment by JakeUskoski** [comment]
I've done the groundwork of writing a solution, which I'll integrate with our codebase to test live tomorrow. As this issue is close to us, I felt it would be beneficial to provide a solution.

**Comment by jimmyjames** [comment]
@JakeUskoski are you interested in making a PR? This is something we should support in the SDK, but we may not be able to get it implemented until after the week of US Thanksgiving. If not we'll target picking it up then (we're going to release 1.25.0 tomorrow, then won't be releasing until after Thanksgiving anyways, fwiw).

**Comment by JakeUskoski** [comment]
@jimmyjames It is a PR, just in draft state at the moment #321 :) I'm testing it now to get the last check before taking it out of draft state.

**Comment by jimmyjames** [comment]
Ah, I just saw the PR now :). I'll take a look when it's out of draft, thanks!!

**Comment by JakeUskoski** [comment]
Finally got a chance to do live testing (and get around spring boot okhttp collisions), and it all looks good, so I've taken the PR out of draft state 🙂

**Comment by JakeUskoski** [comment]
Excited that #321 got merged and put into the 1.26.0 release! When will 1.26.0 be put in Maven Central? Seems like it still isn't there: https://mvnrepository.com/artifact/com.auth0/auth0

**Comment by jimmyjames** [comment]
@JakeUskoski sorry about that! 1.26.0 is in Maven Central now.
