### ISSUE TITLE
Add TokenVerifier for non-OIDC-compliant JWTs

### ISSUE THREAD

**Issue by cihati** [auth0/auth0-java#327]
auth0-java needs the exact same feature @joshcanhelp implemented for auth0-PHP at https://github.com/auth0/auth0-PHP/pull/428

All the required context/implementation details are there.

**Comment by jimmyjames** [comment]
@cihati have you tried using the [java-jwt](https://github.com/auth0/java-jwt) library for general JWT validation? As it allows for greater customizability and is not specific to ID Tokens, that may suit your requirements.

**Comment by jimmyjames** [comment]
Closing this as general JWT verification is available with the [java-jwt](https://github.com/auth0/java-jwt) library.
