### ISSUE TITLE
Support For TLS Version 1.2

### ISSUE THREAD

**Issue by kler** [auth0/auth0-java#337]
From 2021-03-22 Auth0 will be requiring TLS 1.2.

- Does this package support that?
- If yes, from what version is TLS 1.2 supported? _(i.e., who will need to upgrade)_

See
- https://support.auth0.com/notifications/60075b84581057000b4a6739
- https://github.com/auth0/node-auth0/issues/581
- https://github.com/auth0/auth0-PHP/issues/479

**Comment by jimmyjames** [comment]
Hi @kler, yes, this library supports TLS 1.2. This library uses OkHttp, which supports [modern TLS by default](https://github.com/square/okhttp/blob/480c20e46bb1745e280e42607bbcc73b2c953d97/docs/https.md#https). You can read more about HTTPS with OkHttp here if interested. Thanks!
