### ISSUE TITLE
Resend verification Email

### ISSUE THREAD

**Issue by Marcus-Biel-idnow** [auth0/auth0-java#349]
The java client should allow to resend the verification email to the user.

There is an endpoint for that:
https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

But it's not included in the Java library unfortunately.

**Comment by jimmyjames** [comment]
Hi @Marcus-Biel-idnow, the library does provide support for that endpoint in the `JobsEntity`, for example [this method](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/mgmt/JobsEntity.java#L83). Can you verify that meets your needs? Thanks!

**Comment by Marcus-Biel-idnow** [comment]
Thanks! A bit hidden, and I didnt find any documentation about this, but it works, and meets my needs 100% :)
