### ISSUE TITLE
Add `isExpired` to TokenHolder

### ISSUE THREAD

**Issue by pennstatephil** [auth0/auth0-java#356]
### Describe the problem you'd like to have solved
It would be great if we could determine if the token inside a `TokenHolder` was still valid, from a time perspective.

### Describe the ideal solution
An `isExpired()` method for `TokenHolder` that would return true if the `exp` time has passed for the token, otherwise false.

## Alternatives and current work-arounds
Decode the token manually and check the `exp` time like:
`JWT.decode(managementToken.getAccessToken()).getExpiresAt().toInstant().isBefore(Instant.now())`

**Comment by jimmyjames** [comment]
Thanks for the request and information @pennstatephil!

We'll be triaging this request internally. If we do add something like this, we'll need to account for the fact that the access token in the `/oauth/token` response is not always a JWT (it can be an opaque token, as explained nicely on [this community post](https://community.auth0.com/t/expires-in-value-is-always-86400-solved/36830/2)). Perhaps we could calculate an "expiresAt" or "isExpired" from the `expires_in` on the response, if we update the deserialization to timestamp when the response is retrieved and calculate it from that, as [Auth0.Android does](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/request/internal/CredentialsDeserializer.java#L30) (haven't checked the feasibility of this or considered any downsides, just something for us to consider).

**Comment by jimmyjames** [comment]
@pennstatephil we've added an `expiresAt` field to the `TokenHolder` class,  calculated from the time the response is deserialized. Would you like to take a look at https://github.com/auth0/auth0-java/pull/357 and verify that this meets your use case? We'd like to ship a new minor with this change this week, if you have a chance to provide some feedback that would be great, thanks!

**Comment by pennstatephil** [comment]
@jimmyjames The PR looks great- can't wait to give it a try. Thank you for implementing it!

**Comment by lbalmaceda** [comment]
@jimmyjames @pennstatephil this is now released under 1.32.0
