### ISSUE TITLE
Ability to update RuleConfig in Batch to avoid rate limiting

### ISSUE THREAD

**Issue by evankellogg** [auth0/auth0-java#365]
### Describe the problem you'd like to have solved

Add the ability to update Rule Configs in a batch manner in order to avoid rate limiting from the API.

### Describe the ideal solution

Today's endpoint only takes and updates ans single key/value pair for ruleConfig updates which can lead to a rate limit issue when someone would like to update all of their config values at once via code.  It appears the existing SDK defines a RuleConfig constructor to only take in a value and not allow the consumer to define the key on that object.  In order to achieve this without breaking the reasoning for this I would suggest such a batch method to accept a Map<String, String> structure.

**Existing Pattern**
`ruleConfigurationProperties.ruleConfigs.forEach {
            val update = managementAPI.rulesConfigs().update(it.name, RulesConfig(it.value)).execute()
            log.info("Rule Config Updated: {}", update.toString())
}`

**Suggested Addition**
`val configs = ruleConfigurationProperties.ruleConfigs.associateBy({it.name}, {it.value})
managementAPI.rulesConfigs().update(configs).execute()`

## Alternatives and current work-arounds

We are currently sleeping in our existing process in order to avoid the rate limit when making many subsequent calls for updates.

### Additional information, if any

It does not look like there is an HTTP endpoint that currently supports this today, so this would need to be created first in order to support this.

**Comment by jimmyjames** [comment]
Hi @evankellogg, thanks for providing the details on this request. I'll look into this in more detail this week and see if this is something the SDK can/should support in the future. Thanks!

**Comment by jimmyjames** [comment]
Hi @evankellogg, I originally missed that this feature request is really a feature request for the management API itself. The best way to make such a request is through Auth0 support at https://support.auth0.com/. If a new endpoint is added to support this, then we can add support for it to this SDK. Thanks!
