### ISSUE TITLE
resetPassword - method to return a result - the redirect link contained on the email

### ISSUE THREAD

**Issue by javapapo** [auth0/auth0-java#366]
### Describe the problem you'd like to have solved
I would like to programmatically - get the reset password link generated by Auth0 - when I invoke the 

```java
        authAPI.resetPassword(email, "connection").execute();
```

### Describe the ideal solution
Currently when you invoke this call (method), you do indeed get an email containing the `Confirm` button and the url that will redirect you to the change pwd. Is there any chance to get a response on this call the same link contained in the email?

## Alternatives and current work-arounds
I am writting some integration tests, which heavily use the Auth0 API (java flavor). I wanted to test the `Forgot Password Flow` API wise. So I can trigger the `Reset Pwd` flow by invoking this method, but then I need to actually login to my email, read the email to retrieve the link and continue the journey.

**Comment by jimmyjames** [comment]
Hi @javapapo, thanks for providing details here.

Short answer is no, when calling the change password Authentication API endpoint, Auth0 will send an email with the link; this is how the identity of the user is verified. However, as [noted in the Auth0 documentation](https://auth0.com/docs/connections/database/password-change), you can use the [Management API](https://auth0.com/docs/api/management/v2#!/Tickets/post_password_change) to generate a password change ticket, which will generate a URL like the one in the password reset email. Perhaps this can help with your testing efforts?
