### ISSUE TITLE
Obtaining Authorization Code

### ISSUE THREAD

**Issue by tmytlovych-perfectial** [auth0/auth0-java#367]
Is there a way to obtain an Authorization Code?
Like what is returned here via UI login on callback  URL "http://localhost:8888/Callback?code=<auth_code>" 

I have tried with 
```
AuthAPI auth = new AuthAPI("DOMAIN, "ClientId", "ClientSecter");
auth.authorizeUrl("http://localhost:8888/Callback").withResponseType("code").withScope("openid profile email")
                .withAudience("<audience>").build();
```
It returns me a formatted URL - what should I call with that URL to get auth code?

**Comment by jimmyjames** [comment]
Hi @tmytlovych-perfectial,

When you build the authorize URL, it is to be used to redirect the user to the login page. Once the user logs in, the Auth0 authorization server will redirect to your callback URL, and include a one-time use authorization code which can then be used to obtain tokens (with the `exchangeCode` method on the `AuthenticationAPI`). 

More details on the Authorization Code Flow can be found [here](https://auth0.com/docs/flows/authorization-code-flow); hope this helps!

**Comment by tmytlovych-perfectial** [comment]
So, there is no way to get authorization code programmatically?
Only via browser UI login?

**Comment by jimmyjames** [comment]
Correct. That is how the Authorization Code Flow is defined per specification.
