### ISSUE TITLE
doc issue - TokenVerififier withOrganization method

### ISSUE THREAD

**Issue by morad3741** [auth0/auth0-java#387]
Hi, 
Regarding [https://github.com/auth0/auth0-java/blob/master/README.md#organizations](Organizations),

```
IdTokenVerifier.init("{ISSUER}", "{AUDIENCE}", signatureVerifier)
    .withOrganization("{ORG_ID}")
```

its specified to use .withOrganization method but its package private, its not accessible,
I also searched for usages for this method in the code but didn't found any, is that still needed?

Im using version 1.5.0

**Comment by jimmyjames** [comment]
Hi @morad3741, thanks for reaching out. I'm guessing the `withOrganization` method should be public, I'll verify and make that change when I confirm. Thanks!
