### ISSUE TITLE
Identity lacks access_token_secret

### ISSUE THREAD

**Issue by joshua-pevner** [auth0/auth0-java#41]
The Twitter identity provides both an access_token and access_token_secret in its Identity.  Both of these values are necessary when doing third-party auth with Twitter. Unfortunately, the current Identity class only provides the access_token field.  Preferably, another field would be added for access_token_secret.

**Comment by lbalmaceda** [comment]
Hi @joshua-pevner,
With https://github.com/auth0/auth0-java/pull/40 you'll be able to specify additional parameters.

**Comment by lbalmaceda** [comment]
Hi @joshua-pevner 
Thanks for reporting this. I've submitted a PR that parses the extra fields to a Map.

**Comment by joshua-pevner** [comment]
That's awesome, thank you.
