### ISSUE TITLE
Enabled connections are missing when creating an organization

### ISSUE THREAD

**Issue by larsf96** [auth0/auth0-java#425]
### Describe the problem you'd like to have solved

According to the changelog (https://auth0.com/changelog#6BBzbWOwkhEZdzauu2s0Bg), it is now possible to set the enabled connections for an organization directly during the Creation of an organization. This feature is currently not usable with the auth0-java library

### Describe the ideal solution

It should be possible to pass the list of enabled_connections when creating an organization

## Alternatives and current work-arounds

Currently, we have to do separate API calls directly to the management API or set the connections afterwards

**Comment by charliearaya** [comment]
I'm also in need of this feature. I made a work-around by extending Organization and adding the extra value:

import com.auth0.json.mgmt.organizations.EnabledConnection;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AuthOrganization extends com.auth0.json.mgmt.organizations.Organization {
    @JsonProperty("enabled_connections")
    private List<EnabledConnection> enabledConnections;
}`

**Comment by poovamraj** [comment]
Hi @charliearaya, We have released a new version ([1.42.0](https://github.com/auth0/auth0-java/releases/tag/1.42.0)) which should support this. Do let us know if you need any more help and thanks a lot for your contribution!
