### ISSUE TITLE
Client response model class is missing certain fields

### ISSUE THREAD

**Issue by bhatmadhavi** [auth0/auth0-java#443]
### Describe the problem you'd like to have solved

This class `com.auth0.json.mgmt.client.Client` (https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/client/Client.java) is missing following fields, that auth0 management API do provide in the client response.
Missing fields:
```
"tenant": type - String
"global": type - Boolean
"cross_origin_auth": type - Boolean
"callback_url_template": type - Boolean
```
Sample response as per auth0 docs, does contain these values. But the pojo class does not include them
https://auth0.com/docs/api/management/v2#!/Clients/get_clients

### Describe the ideal solution
Simple solution is to include these fields into `com.auth0.json.mgmt.client.Client` https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/client/Client.java

**Comment by poovamraj** [comment]
Hi @bhatmadhavi we have added the missing parameters in this PR - https://github.com/auth0/auth0-java/pull/444

Thanks for raising this! this should be in our next release of the SDK. we will close this issue now but feel free to reopen it if required
