### ISSUE TITLE
Add support for `/users/{user_id}/authenticators` endpoint to retrieve all Guardian Enrollments

### ISSUE THREAD

**Issue by jdk2pq** [auth0/auth0-java#472]
### Describe the problem you'd like to have solved

Our use case is that we would like to retrieve the phone number stored for a user on Auth0. Since we require mobile MFA (with email MFA as a fallback), we should be able to get this number from the Guardian Enrollments. However, the `/users/{user_id}/enrollments` endpoint only returns the first confirmed enrollment in the user's list of MFA enrollments, and for users who use a social sign-on provider (e.g. Google), the first enrollment in the list is their verified email address, so this endpoint will not work for getting those users' phone numbers.

In the Auth0 Community's FAQ's, there is a solution that uses the `/users/{user_id}/authenticators` endpoint described [here](https://community.auth0.com/t/how-to-get-all-the-guardian-enrollments-for-a-user-via-api/85337), [here](https://community.auth0.com/t/how-to-get-sms-mfa-enrollments-with-full-phone-numbers/94222), and finally [here](https://community.auth0.com/t/when-will-api-v2-users-userid-authenticators-be-documented/52722). That will return the full list of enrollments for a user and allow us to filter down to just the SMS/Voice enrollments to get the user's phone number.

### Describe the ideal solution

A new method is added to `UsersEntity.java` that calls the `/users/{user_id}/authenticators` endpoint and returns the full list of authenticators for the user.

## Alternatives and current work-arounds

Currently, we call the endpoint in our own code outside of the `auth0-java` SDK.

### Additional information, if any

- An old PR that added support for this endpoint in the Auth0 Go SDK: https://github.com/go-auth0/auth0/pull/110

**Comment by jimmyjames** [comment]
:wave: Hey @jdk2pq, thanks for all the info and context.

I know this may sound pedantic, but our SDKs will support endpoints once they are fully supported and documented. Given that the `/users/{user_id}/authenticators` endpoint is not publicly documented yet, we will not be adding it to this library. I recognize given some of the community responses it may be OK to use, but until it is officially released and documented, our SDKs will not implement it. Hope you understand, thanks!
