### ISSUE TITLE
Feature request: add support for the /delegation API

### ISSUE THREAD

**Issue by bradleybuda** [auth0/auth0-java#48]
I'd like to use this SDK to obtain an access_token for a refresh_token - it looks like in Auth0 this is done with the [/delegation API](https://auth0.com/docs/api/authentication#delegation). Is it possible to add that to the Java SDK so I don't have to roll my own implementation? Thanks!

**Comment by lbalmaceda** [comment]
Hi @bradleybuda. 
I'll mark it as a feature request. In the meantime you can make a `POST` request to the `/oauth/token` endpoint with the following body:

```json
{
   "grant_type":"refresh_token",
   "client_id":"YOUR_CLIENT_ID",
   "refresh_token":"YOUR_REFRESH_TOKEN"
}
```
