### ISSUE TITLE
HTTP response status in exception

### ISSUE THREAD

**Issue by rafalwrzeszcz** [auth0/auth0-java#49]
How to get a response status in case of error response? `Auth0Exception` is just an `IOException`, no information about reason - it's critical to know if it's 403, or 404 (or anything else).

**Comment by lbalmaceda** [comment]
Hi @rafalwrzeszcz 
That kind of exception is called `APIException`. You can try to catch it first as it extends `Auth0Exception`, and call `getStatusCode()` to know the status code. [ref](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/exception/APIException.java#L44).

**Comment by rafalwrzeszcz** [comment]
Ok, sorry, didn't notice this subclass, as all `throws` contracts claims just `Auth0Exception`. I see big improvement form `0.4.0` to `1.0.0`, but I miss some migration documentation.

**Comment by lbalmaceda** [comment]
Thanks for the feedback! 🎉  I'll take note and update the docs in the future.
Cheers.
