### ISSUE TITLE
Add support for Enterprise Connections show_as_button field

### ISSUE THREAD

**Issue by vs-gtadeu** [auth0/auth0-java#492]
### Describe the problem you'd like to have solved

My team's solution is using Auth0 to create database and SAML connections for our customers. In order to display the SAML connection as an option during login, we allow customers to display it as a button via the `show_as_button` flag.
However, the [Connection](https://github.dev/auth0/auth0-java/blob/master/src/main/java/com/auth0/json/mgmt/Connection.java#L1) class currently doesn't include this field, which creates a bit of problem for us to provide that feature.

### Describe the ideal solution

It would be nice if the `show_as_button` field were available in that class so we wouldn't need to rely on workarounds as a way to consume it.

## Alternatives and current work-arounds

We are able to overcome this issue by extending the `Connection` class and adding that field:

```java
public class EnhancedConnection extends Connection {

    @JsonProperty("show_as_button")
    private Boolean showAsButton;

}
```

Although this works, it creates some complexity in reading the connection data when getting a list of connections or getting a connection by ID.

### Additional information, if any

This field is also not documented in the [Auth0 Management API docs](https://auth0.com/docs/api/management/v2#!/Connections/patch_connections_by_id), so we are a bit concerned the field is not intended to be consumed via the Management API. We hope it is just something that Auth0 hasn't documented yet.

**Comment by jimmyjames** [comment]
👋 Hi @vs-gtadeu, thanks for raising this. As you noted this field is not publicly documented. As such, the SDK won't add support until it is publicly documented/supported - in the meantime extending the `Connection` class seems like the best approach. If/when I learn any additional info on plans/timelines to support that property, I'll let you know. Thanks!
