### ISSUE TITLE
Add support for filters in LogStreams

### ISSUE THREAD

**Issue by clementdenis** [auth0/auth0-java#493]
### Describe the problem you'd like to have solved

The SDK currently does not support [filters in LogStreams](https://auth0.com/docs/api/management/v2#!/Log_Streams/post_log_streams).

### Describe the ideal solution

Add the field for filters in LogStreams.

### Additional information, if any

The API explorer does not define clearly what is the structure of the filter (just an `array[object]`).
So I have added the field [in this commit](https://github.com/clementdenis/auth0-java/commit/ba70c08888e45bb459d09ab4eec45e98e3ca8186) and it works for me, but I won't be submitting a PR as I don't know if it's correct for all cases.

**Comment by jimmyjames** [comment]
Thanks @clementdenis for the request and the implementation! I've made #494 to add support for the log stream filters.

**Comment by jimmyjames** [comment]
This is now available in the v2 beta! See here for more information, and in addition to this change, please let us know what you think of the new beta version!
