### ISSUE TITLE
Support Create/Update User Authentication Methods (Mgmt API)

### ISSUE THREAD

**Issue by phippsnatch** [auth0/auth0-java#504]
### Describe the problem you'd like to have solved

To be able to maintain extra login factors, via some of the newly available Management API requests:
- [create an authentication method for a given user](https://auth0.com/docs/api/management/v2#!/Users/post_authentication_methods)
- [update all authentication methods by replacing them with the given ones](https://auth0.com/docs/api/management/v2#!/Users/put_authentication_methods)

n.b. Similar to [this](https://github.com/auth0/auth0-java/pull/484), but for the Management API.

### Describe the ideal solution

Would probably be made available on `com.auth0.client.mgmt.UsersEntity` (similar to `#getEnrollments(String)`)?

### Alternatives and current work-arounds

Workaround: can misuse the [user import command](https://javadoc.io/static/com.auth0/auth0/2.0.0-beta.0/com/auth0/client/mgmt/JobsEntity.html#importUsers(java.lang.String,java.io.File,com.auth0.client.mgmt.filter.UsersImportOptions)) to set a phone number for SMS factor.

**Comment by jimmyjames** [comment]
Thanks @phippsnatch! Yes, I see there are some new endpoints related to authentication factors in the Management API. We will work to get these added to v2. 

We'll also add support via that PR for the Auth APIs you referenced. Thanks!

**Comment by jimmyjames** [comment]
This is now available in `2.0.0-beta.1` via #506 🎉
