### ISSUE TITLE
v2 Beta Available!

### ISSUE THREAD

**Issue by jimmyjames** [auth0/auth0-java#509]
🎉 We are excited to announce the availability of  `auth0-java` v2 beta! 🎉 

The version 2 release includes several notable improvements, including:

- Requests can now be configured with additional parameters and headers, without needing to downcast to `CustomRequest`.
- Responses are now wrapped in a new `com.auth0.net.Response` type, which provides information about the HTTP response such as headers and status code.
- A new `Auth0HttpClient` interface has been added, along with a default implementation (`DefaultHttpClient`), enabling easy HTTP configuration and reuse among API clients.
- The `AuthAPI` client no longer requires a client secret, enabling support for APIs and scenarios where a secret is not required.
- MFA APIs now supported for both the `AuthAPI` and `ManagementAPI` clients!

As a major release (and the first major release of this library in six years!), it does include breaking changes. Please see the [migration guide](https://github.com/auth0/auth0-java/blob/v2-dev/MIGRATION_GUIDE.md) for information on updating your application to use v2.

We'd really appreciate your feedback! The v2 beta is available by updating your dependency to version `2.0.0-beta.1`, and please follow the [releases page](https://github.com/auth0/auth0-java/releases) for any additional v2 beta releases.

Thanks, and let us know how you are liking v2!

**Comment by jimmyjames** [comment]
2.0.0 is now available for general release 🎉

**Comment by backjo** [comment]
@jimmyjames fyi - the main README indicates that V2 is still a beta version and warns against using it
