### ISSUE TITLE
Add possibility to specify arbitrary client_id for resetPassword method, as argument

### ISSUE THREAD

**Issue by artyk404** [auth0/auth0-java#510]
### Describe the problem you'd like to have solved

Hello there, we use `auth0-java` to interact with Auth0 API. To trigger user password change flow we call [resetPassword](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/auth/AuthAPI.java#L316) method. We have many SPA applications and single "machine-to-machine" application. We allow access to "Auth0 Management API" only to this "machine" application. In current scenario when "machine" application triggers reset password flow and user changes password, they only see confirmation text like "Your password changed successfully" without being redirected to actual login page. But that is actually what we want - to redirect user to "needed" application's login url. As I learned ["Change Password" API](https://auth0.com/docs/api/authentication#change-password) accepts optional (and recommended) parameter `client_id` to specify what client_id (SPA application) to associate with password change flow.

However , **the problem**: [`resetPassword`](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/auth/AuthAPI.java#L316) method doesn't have possibility to specify this dynamic `client_id` and I believe uses same [`client_id`](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/auth/AuthAPI.java#L327) as for interaction with API, hence no redirect to any login page after password change, because "machine" application doesn't have any login urls configured.

### Describe the ideal solution

Add possibility to specify arbitrary `client_id` for [`resetPassword`](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/auth/AuthAPI.java#L316) method, as argument.

## Alternatives and current work-arounds

N/A
### Additional information, if any

- Do you think my observation above is correct and such approach makes sense?
- To make it faster, we can contribute to implementation of this feature request

**Comment by jimmyjames** [comment]
👋 hi @artyk404, thanks for the info and request! Yes, I think it makes sense to add a new method that supports specifying a client ID. I've made a PR for this in #511, if you want to take a look and ensure it addresses your use case, that would be great!

**Comment by jimmyjames** [comment]
Hey @artyk404, we plan to release a new v2 beta with this change this week. And V2 GA is scheduled for next week.

**Comment by jimmyjames** [comment]
Juste an update - we plan to release a new beta version tomorrow, and v2 GA week of Feb 20.
