### ISSUE TITLE
LogEvent doesn't have the fields returned from v2/logs endpoint.

### ISSUE THREAD

**Issue by victorhua** [auth0/auth0-java#519]
### Describe the problem you'd like to have solved

According to https://github.com/auth0/auth0-java/blob/39114f4493d43ee69ee6660ae5aafc0e54b06ed3/src/main/java/com/auth0/json/mgmt/logevents/LogEvent.java and https://auth0.com/docs/api/management/v2#!/Logs/get_logs. 

LogEvent POJO doesn't have the following fields:

- description
- connection
- connection_id
- hostname
- audience

### Describe the ideal solution

Please add them to LogEvent POJO.

**Comment by jimmyjames** [comment]
👋 thanks for raising @victorhua! #521 adds these fields, feel free to have a look!
