### ISSUE TITLE
Add groups and dn to User Pojo

### ISSUE THREAD

**Issue by victorhua** [auth0/auth0-java#538]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-java#readme) and [Examples](https://github.com/auth0/auth0-java/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-java/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We are calling GET api/v2/users endpoint to get user information.

It seems [User](https://github.com/auth0/auth0-java/blob/58182fb444068311000d922cc7e38691d56c3eeb/src/main/java/com/auth0/json/mgmt/users/User.java) doesn't have groups and dn properties. 

### Describe the ideal solution

Please add them.

**Comment by jimmyjames** [comment]
👋 hi @victorhua, thanks for raising! Can you provide an example of these properties as returned by the API? I don't see a `group` or `dn` property when I make a request to list users. Thanks!

**Comment by victorhua** [comment]
I think these fields are only available when the connection is a SAML, it may also depend on the SAML configuration.
example:
#
{
...
 "Groups": [
        “Dev”,
        “Admin”
    ],
    "dn": "CN=TEST,OU=Testing,OU=HQ,OU=Users,OU=Test_HQ,OU=Testing,DC=US,DC=test”,
...
}
# 
Is it possible to pass in a customized POJO class in this case?

**Comment by jimmyjames** [comment]
Hi @victorhua, thanks for the info! We'll see if there's a nice way we can support this.

**Comment by jimmyjames** [comment]
Ah, this has come up before and was addressed in https://github.com/auth0/auth0-java/pull/56. You can use the `getValues()` method on the `User` to get a map of values, which in this case would contain the `groups` array and `dn` value. Let me know if that works for you, thanks!

**Comment by jimmyjames** [comment]
Closing as this info can be retrieved via the `getValues()` method discussed above.
