### ISSUE TITLE
query for search users is not correctly translated

### ISSUE THREAD

**Issue by asmolabs** [auth0/auth0-java#54]
Hi,

I had a query "user_metadata.\*environmentType:"DEMO""

This query works in the Management test api

Call failed with sdk because url creation

Web management api send :: user_metadata.%5C*environmentType%3A%22DEMO%22

Your sdk send :: user_metadata.\\*environmentType:%22DEMO%22

Best regards

**Comment by lbalmaceda** [comment]
Hi @asmolabs thanks for reporting this. I've reproduced the issue, it seems it's not properly encoding the URL query parameters. I'll try to fix it for the next release.
Cheers.
