### ISSUE TITLE
Add ability to set only certain properties when updating a user.

### ISSUE THREAD

**Issue by brettcooper** [auth0/auth0-java#58]
When calling the management API to update a user, I am always receiving the following exception:

com.auth0.exception.APIException: Request failed with status code 400: Payload validation error: 'Additional properties not allowed: logins_count,last_login,identities,updated_at,created_at,nickname,name,picture,user_id (consider storing them in app_metadata or user_metadata. See "Users Metadata" in https://auth0.com/docs/api/v2/changes for more details)'.

According to the Auth0 API [documentation](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id), it looks like we should only be sending properties for the user that have changed (e.g. - email, email_verified, user_metadata, etc.)  But, with the current API's implementation, this is not possible and I have had to write my own REST call to make this work (I am just trying to update a user so that user is blocked).

Something similar to this should work:

    public Request<User> update(String userId, String json) {
        Asserts.assertNotNull(userId, "user id");
        Asserts.assertNotNull(json, "json");
        String url = this.baseUrl.newBuilder().addPathSegments("api/v2/users").addPathSegment(userId).build().toString();
        CustomRequest<User> request = new CustomRequest(this.client, url, "PATCH", new TypeReference<String>() {
        });
        request.addHeader("Authorization", "Bearer " + this.apiToken);
        request.setBody(json);
        return request;
    }

**Comment by lbalmaceda** [comment]
@brettcooper The server won't let you call that endpoint sending any of those attributes. When you call PATCH you just send the attributes that you want to change, not the whole user object.. In the practice you'd do that if the Http method is PUT. So if you're trying to change the blocked attribute, just send that.

**Comment by brettcooper** [comment]
@lbalmaceda Is it currently possible to do this with the Auth0 Java client?  If so, can you point me in the right direction or can you provide an example?

**Comment by lbalmaceda** [comment]
User should have a public constructor with no args but it seems it's missing. Anyway, if you see the code the same can be achieved by passing a null connection.

```java
        ManagementAPI managementAPI = new ManagementAPI("the_domain","the_api_token");
        User user = new User(null);
        user.setBlocked(true);
        managementAPI.users().update("your_user_id", user).execute();
```

**Comment by brettcooper** [comment]
Perfect.  Thanks @lbalmaceda !

**Comment by sid027** [comment]
can someone let me know what is wrong trying to achieve the same thing with cURL. I get the same error.

```curl -X PATCH -H "Authorization: Bearer $AUTH0_TOKEN" "Content-Type: application/json" -d '{"blocked": true}' 'https://auterion-suite.eu.auth0.com/api/v2/users/{id}'```
(id is replaced with the user_id).

Error:
```curl: (3) Port number ended with ' '
{"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Additional properties not allowed: {\"blocked\": true} (consider storing them in app_metadata or user_metadata. See \"Users Metadata\" in https://auth0.com/docs/api/v2/changes for more details)'.","errorCode":"invalid_body"}```
