### ISSUE TITLE
Use different POJO for PATCH /api/v2/users

### ISSUE THREAD

**Issue by hzalaz** [auth0/auth0-java#61]
Since PATCH users has some strict rules we could use a different POJO to make it simpler to modify the user without knowing those rules

**Comment by kagof** [comment]
Would this be something that is still wanted? I'd be happy to make PR for it if so!

**Comment by lbalmaceda** [comment]
@kagof I think the original intention of this issue was to have some POJO that acted as a generic map of String/Object entries. But I rather leave this for the next major.
