### ISSUE TITLE
How to request Auth0 to resend the verification email, via Java API?

### ISSUE THREAD

**Issue by alump** [auth0/auth0-java#62]
I did not find any way to resend the validation email with Java API.

Also following method is not available via Java API.
https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

**Comment by lbalmaceda** [comment]
@alump there's no way to trigger it from this SDK. Back when we designed it we thought that the Jobs API wasn't so useful, though I'll consider adding this single method. For the time being, you'll have to make that request manually following the docs that you've linked above. I'll leave this open as a reminder.
Cheers.

**Comment by Bronsa** [comment]
Any updates on this?

**Comment by lbalmaceda** [comment]
@Bronsa I'll see if the next week I can give it a look. PRs are welcome though.

**Comment by Bronsa** [comment]
👍 , I'll see if I have some time before you do then

**Comment by kanikaar** [comment]
Dont know about java api but a simpler way is as i commented here using Auth0 Rule:
https://stackoverflow.com/a/49143694/1685678

**Comment by lbalmaceda** [comment]
@kanikaar Although that rule works you're not triggering it with a "user action". Instead, you are sending an email after every failed login which IMO is kind of spammy 😅. Be aware that email providers block such behaviors and may treat your email source address as SPAM.

**Comment by minhlongdo** [comment]
@lbalmaceda is this feature being internally worked on?

**Comment by lbalmaceda** [comment]
@minhlongdo this feature is being tracked internally, but there is no progress so far, no.

**Comment by minhlongdo** [comment]
@lbalmaceda so then I will pick it up, would that be ok? :)

**Comment by lbalmaceda** [comment]
of course! 🎉 PRs are more than welcome. Feel free to copy/paste an existing entity such as `LogEventsEntity` and keep 1 POST method to send the verification email. The entity should be named  `JobsEntity` and have it's behavior tested. I'll be reviewing your PR.

**Comment by jeacott1** [comment]
+1 this really should exist, as should the entire api.

**Comment by minhlongdo** [comment]
@jeacott1 Yh I was thinking of that as well, I think I could pick those up if you guys don't mind?
@lbalmaceda I got a PR for you https://github.com/auth0/auth0-java/pull/120, let me know if something is wrong, it is my first time contributing to opensource :)

**Comment by ewal31** [comment]
Is this ever going to be reviewed and merged?

**Comment by minhlongdo** [comment]
@ewal31 I don't know, the PR has been open for a while now, @lbalmaceda is the PR currently actively under review?
