### ISSUE TITLE
Get AD connection's provisioning_ticket_url property

### ISSUE THREAD

**Issue by marci74** [auth0/auth0-java#66]
I see no way to get the value of the "provisioning_ticket_url" property of an AD connection entity. Could you please add it to the connection POJO? For a common solution it might make sense to have the possibilty to use custom POJOs for the deserialization. Thanks.

**Comment by unnamed38** [comment]
I would really like to have this feature as well

**Comment by lbalmaceda** [comment]
I just released 1.2.0 on Bintray. In a few hours, it should be available on Maven as well.
