### ISSUE TITLE
Social login using the java sdk

### ISSUE THREAD

**Issue by kmuthukrishnan** [auth0/auth0-java#69]
@lbalmaceda,

We are using the sdk provided for our login and registration (Thanks!). We also need to implement social login - facebook and google based login & registration in our app. 

Can you please help us understand how we can implement the same?

regards
Krithika

**Comment by lbalmaceda** [comment]
The easiest way is to call the Auth0 Hosted Login Page by using the `AuthorizeURLBuilder` as explained [here](https://github.com/auth0/auth0-java#authorize---authorize). If you pass a connection name (i.e. `auth0` or `facebook`) it will use that one, but if you don't set it the widget will show every connection enabled for that client. I suggest you follow the [quickstarts](https://auth0.com/docs) as they first explain this case I mention, and any doubt check [support](https://support.auth0.com) or our [community](community.auth0.com)
