### ISSUE TITLE
Improve support for PKCE flow

### ISSUE THREAD

**Issue by mattjbray** [auth0/auth0-java#73]
It would be nice if this library would better support the PKCE flow. Specifically:

* Allow instantiating `AuthAPI` without a client secret.
* Library functions for creating the `code_verifier` and `code_challenge` as documented in the Java sample code [here](https://auth0.com/docs/api-auth/tutorials/authorization-code-grant-pkce#1-create-a-code-verifier).
* Add a `withCodeChallenge` method to `AuthorizeUrlBuilder` (perhaps `withParameter("code_challenge_method", "S256")` could be called automatically when using `withCodeChallenge`).
* Add a method to the `AuthAPI` class that additionally sets the `code_verifier` parameter, e.g.:
   ```java
   public AuthRequest exchangeCodeWithVerifier(
       String code, String redirectUri, String codeVerifier)
   ```

**Comment by lbalmaceda** [comment]
@mattjbray This library is preferred for server side code that's why we require the `client_secret` at first and send it on the authentication calls. PKCE flow is meant to be used from native clients, like a mobile app. If that's your case you might find this other [library](https://github.com/auth0/auth0.android) helpful.

**Comment by mattjbray** [comment]
@lbalmaceda This is for a desktop Java application.

**Comment by chrisvire** [comment]
@lbalmaceda What are Java Desktop applications supposed to use?

**Comment by lbalmaceda** [comment]
Definitely PKCE for now. We recently discussed adding this to the SDK. The only caveat I see is flows should be somewhat separated so people that want to use this SDK for a backend app don't end up using the PKCE flow by mistake, or vice-versa. I've added this as an item to our backlog. I'll keep you updated.

**Comment by chrisvire** [comment]
@lbalmaceda That would be great!  I have an immediate need for this.  I need to release a product next month with this feature.  How can I help? Could I interact with the development team on this to come up with a design?

**Comment by chrisvire** [comment]
@mattjbray Did you come up with an alternative?  I didn't see a fork of the library in your public github account.

**Comment by chrisvire** [comment]
@lbalmaceda You said that added this as an item to your backlog.  What timeframe do you thing it will be before it could be included in this library?

**Comment by mattjbray** [comment]
@chrisvire We just had a private implementation of this guide: https://auth0.com/docs/api-auth/tutorials/authorization-code-grant-pkce. It's perfectly possible to do, I just opened this issue because it would be nice to have it out-of-the-box.

We've since moved our application from Java to OCaml so I haven't really been following this.

**Comment by chrisvire** [comment]
@mattjbray Would you be able/willing to share your private implementation as a code sample?

**Comment by chrisvire** [comment]
@mattjbray I got something to work. Thanks.

**Comment by lbalmaceda** [comment]
@mattjbray @chrisvire After discussing this we've reached to the conclusion that Java for Desktop is not a platform we would like to provide OOTB support for with this SDK. We will keep supporting backend flows.

You can always fork the library and make the necessary changes (mentioned on the original post) if this is a blocker to you. I also suggest you raise your need directly with our Product team by dropping them a message here via this form: https://auth0.com/feedback. They can evaluate and prioritize this feature request and give you a more detailed response.

**Comment by maffelbaffel** [comment]
> Java for Desktop is not a platform we would like to provide OOTB support for with this SDK
We are currently developing a MultiPlatform App using jetbrains compose for Android + Desktop + Web and would really appreciate if you think about this decision again. It would be much easier to integrate Auth0 in such applications!
