### ISSUE TITLE
no setter for User.id

### ISSUE THREAD

**Issue by jeacott1** [auth0/auth0-java#79]
for testing purposes it would be helpful if there was some way other than using jackson to magically set the userId field for an auth0 User object.

**Comment by lbalmaceda** [comment]
No that I can imagine as that is an attribute set only by the server. Either parse a JSON with the values you need for your tests or mock the User instance and make it return a given id when `user.getUserId()` is called.

**Comment by jeacott1** [comment]
nice to see this was actually added. https://github.com/auth0/auth0-java/commit/887b0e7857a250d2664803f95d48bb93d0d2ebed

**Comment by lbalmaceda** [comment]
@jeacott1 yeah there was a use case I wasn't aware of so we added it 👍
