### ISSUE TITLE
How do I rotate the managementApi token with this lib?

### ISSUE THREAD

**Issue by jeacott1** [auth0/auth0-java#80]

**Comment by lbalmaceda** [comment]
You would [blacklist the access token](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/mgmt/BlacklistsEntity.java#L53) or [delete the client grant](https://github.com/auth0/auth0-java/blob/master/src/main/java/com/auth0/client/mgmt/ClientGrantsEntity.java#L78). More info [here](https://auth0.com/docs/api-auth/blacklists-vs-grants).

**Comment by jeacott1** [comment]
I think you missed my point. the token expires but I need my service to continue working.
I've had to roll my own wrapper for your sdk in order to keep a consistently available managementApi with a non expired token on call. There is no built in functionality and no way to hand a new token to the ManagementAPI object. once its token expires the whole thing needs to be replaced. cumbersome and annoying. exactly the kind of situation an sdk should make easy.
