### ISSUE TITLE
Feature request: ability to introspect management API User connection

### ISSUE THREAD

**Issue by gotwalt** [auth0/auth0-java#84]
Though the connection is in memory if I've fetched a user, there's no way to actually read the field unless I dump it to JSON. Is there a reason for this design choice?

https://github.com/auth0/auth0-java/blob/5f44c0dc5ce10cbea42a910d0196e32f3870afd3/src/main/java/com/auth0/json/mgmt/users/User.java#L516

**Comment by gotwalt** [comment]
Ahh, it's found inside the array of identities. Makes sense.

**Comment by lbalmaceda** [comment]
The problem with this first API is that the same POJO is used to
- create users
- retrieve users

Create has it's own rules, like always requiring a `connection`. If the user is part of a db connection, the `email` and `password ` is also required. But when you read the user back, you get the info of each provider used to log in in the `identities` array.

On a future version I'll change this to use 2 separate classes.
