### ISSUE TITLE
Support for new users-by-email endpoint?

### ISSUE THREAD

**Issue by neshanjo** [auth0/auth0-java#85]
Hi,

when will the new users-by-email endpoint be supported?  
https://auth0.com/docs/api/management/v2#!/Users_By_Email/get_users_by_email 

Kind regards,
Johannes

**Comment by lbalmaceda** [comment]
We're looking to support it soon. I hope by next Friday.

**Comment by neshanjo** [comment]
That's great!

**Comment by neshanjo** [comment]
Ok. It's merged now. Thank you! When will it be released?

**Comment by lbalmaceda** [comment]
Hey. I want to fix this https://github.com/auth0/auth0-java/issues/86 as well before the next release, but I'm holding for a response from other team. Hopefully before next Friday 🤞
