### ISSUE TITLE
SignUp response is a VoidRequest

### ISSUE THREAD

**Issue by cesartl** [auth0/auth0-java#86]
Currently the `signUp call` returns a `VoidRequest` even though the documentation specifies the server responds with a message like

```JSON
{
  "_id": "58457fe6b27...",
  "email_verified": false,
  "email": "test.account@signup.com"
}
```

It would be better for `signUp` to return something like `CustomRequest<User>` so the newly created user id can be accessed.

**Comment by lbalmaceda** [comment]
Totally. I missed this method. I think `username` is also returned when you signup with a username. Will leave this open as a reminder. Thanks
