### ISSUE TITLE
New release 1.3.2 containing listByEmail?

### ISSUE THREAD

**Issue by TiGz** [auth0/auth0-java#90]
Hi,

I want to call the users().listByEmail endpoint but the relevant method seems to be missing from the latest release:

        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>auth0</artifactId>
            <version>1.3.1</version>
        </dependency>

Could we have a new release please? Or am I missing something?

Thanks.

**Comment by lbalmaceda** [comment]
Probably will release on Wednesday these 2 things.
Related: https://github.com/auth0/auth0-java/issues/85

**Comment by richard-hulm** [comment]
+1 this will be useful
