### ISSUE TITLE
Support for http proxy

### ISSUE THREAD

**Issue by sbityakov** [auth0/auth0-java#91]
Looking at the code there is no way to set up an http proxy for AuthAPI to use.  Would like to be able to set proxy (URL or host/port) on the AuthAPI object.  The code I was reviewing is in AuthAPI constructor:
```
         client = new OkHttpClient.Builder()
                .addInterceptor(logging)
                .addInterceptor(telemetry)
                .build();
```
Please let me know if I'm missing something here.  Thanks!

**Comment by sbityakov** [comment]
OK, thanks for the response.  I'll roll my own for now.

**Comment by davet54321** [comment]
Would it be possible to solve this in 2 steps instead of 1. First step just expose ability to use proxy (without authentication). Second step handle the more complicated case of authenticated proxy.

I have a use case which needs a proxy (but not an authenticated one), so just solving the first case would be enough for me.

**Comment by jcd006** [comment]
@lbalmaceda We have a similar requirement to call Auth0 through a forward proxy for ManagementAPI and AuthAPI.

Can the httpclient be exposed through a constructor so that I can set my own proxy?

**Comment by sappenin** [comment]
Echoing the request above, possibly doing something like this:

```
public ManagementAPI(String domain, String apiToken, OkHttpClient.Builder okHttpClientBuilder) {
        Asserts.assertNotNull(domain, "domain");
        Asserts.assertNotNull(apiToken, "api token");
        Asserts.assertNotNull(okHttpClientBuilder, "okHttpClientBuilder");

        this.baseUrl = createBaseUrl(domain);
        if (baseUrl == null) {
            throw new IllegalArgumentException("The domain had an invalid format and couldn't be parsed as an URL.");
        }
        this.apiToken = apiToken;

        telemetry = new TelemetryInterceptor();
        logging = new HttpLoggingInterceptor();
        logging.setLevel(Level.NONE);
        client = okHttpClientBuilder
                .addInterceptor(logging)
                .addInterceptor(telemetry)
                .build();
    }
```

**Comment by jcd006** [comment]
@lbalmaceda I've raised another MR. #150 This one doesn't expose any okhttpclasses. It uses java.net.Proxy for proxy and java.net.PasswordAuthentication for proxy authentication.
