### ISSUE TITLE
Request: publish new release with v2/users-by-email endpoint

### ISSUE THREAD

**Issue by drazzib** [auth0/auth0-java#94]
Hi!

As you might already know, Auth0 API now provide a new - optimized - endpoint to fetch user by their emails : https://auth0.com/docs/api/management/v2#!/Users_By_Email/get_users_by_email

I've seen there is some existing code (7625adb4596a349f434f5226db71142aeb48c6b5) for supporting this new API in auth0-java. @lbalmaceda, do you plan to publish a new release soon ?

Regards,

**Comment by lbalmaceda** [comment]
Released 1.4.0. Read the changelog for more information.
