### ISSUE TITLE
Support for POST /api/v2/jobs/users-exports

### ISSUE THREAD

**Issue by jebbench** [auth0/auth0-java#95]
Since we're now unable to query the management api to find users based on our own internal ID we're forced to create our own local cache of user accounts; the Auth0 recommended way to do this is to use the export job method on the management API however this doesn't appear to be supported by the Java API.

We need at least support for:
 - https://auth0.com/docs/api/management/v2#!/Jobs/post_users_exports
 - https://auth0.com/docs/api/management/v2#!/Jobs/get_results

**Comment by lbalmaceda** [comment]
@jebbench we're not planning to add this in the near future. I'll tag it as a nice to have for now.

**Comment by jebbench** [comment]
@lbalmaceda - no worries; we'll hammer the https://auth0.com/docs/api/management/v2#!/Users/get_users in the meantime.

**Comment by neshanjo** [comment]
Any news on this? I'm a bit astonished that this endpoint still does not exist. 
I think, having a complete API is not "nice-to-have", but rather something a (paying) user can expect.

**Comment by levyshachar2** [comment]
Hi , we actually also have the same need for this API.
Is this on the road map?

Thanks

**Comment by lbalmaceda** [comment]
@levyshachar2 not specifically on the roadmap but we have a bunch of changes and hopefully will be available by EOY.

**Comment by dbt** [comment]
Would also appreciate support for this.

**Comment by lbalmaceda** [comment]
Apologies for such a long delay. I'm going to update the Jobs entity and add at least the ones required here by you on the first comment @jebbench. While trying that I found that the "get results" endpoint is no longer present in the swagger docs and I wonder what the replacement is today.
If someone of you is familiar with the jobs API and would like to comment, I'm reading.

In the meantime, I'll focus the work on this PR
